import type { Metadata } from "next";
import "@/styles/globals.css";
import { MainLayout } from "@/components/layout";
import Providers from "@/components/Providers";
import "react-ripple-click/dist/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh flex flex-col">
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
